### ISSUE TITLE
Strange enemies on level 1

### ISSUE THREAD

**Issue by vi** [Smujb/yet-another-shattered-dungeon#13]
Typically (at least in Shattered PD) I expect the first level to contain just 10 rats that cumulatively give experience points for 1 level up.

Currently (e553e8ca0894c578f507afca8832a3c7798adfea) it hovewer contains prison's bots and warlocks instead. They are both ranged enemies, it is inconvenient for altar rooms. They are weak, typically deal 0 damage and die in one wand of magic missile hit. When defeated however they give lucrative EXP - each kill is one level up (capped at level 4).

---

Also previous game finished strangely in Metropilis: screen getting red (and vibrator shaking) and something hitting the hero over and over, ultimately draining HP from full to zero during about 2 seconds, without giving any initiative. "Slain by: Golem". Golem? I supposed they only can be in rooms, not in corridors.

**Comment by Smujb** [comment]
Yeah, this isn't in the latest 2 updates.
