### ISSUE TITLE
Scrapping a weapon with a full inventory does not drop the scrap

### ISSUE THREAD

**Issue by ShareDVI** [Smujb/yet-another-shattered-dungeon#14]
Of course, it'd have to be an equipped weapon to keep inventory full.

What I expected: weapon consumed, scrap is dropped (like with alchemy)

What I got: weapon consumed, no scrap.

**Comment by Smujb** [comment]
Fixed by: https://github.com/Smujb/yet-another-shattered-dungeon/commit/1fe66a179c4f7984f9fe495a2ef61137c86aebf1
