### ISSUE TITLE
Undiving near the edge of the  water level puts the character into a wall sometimes

### ISSUE THREAD

**Issue by ShareDVI** [Smujb/yet-another-shattered-dungeon#17]
Screenshot attached. ![photo_2020-06-19_20-19-06](https://user-images.githubusercontent.com/2362022/85162608-51fc7b00-b26a-11ea-927b-f54829592db2.jpg)

**Comment by ShareDVI** [comment]
Another related bug is that undiving puts me on a non-water tiles. I undived on top of a pit ffs

**Comment by Smujb** [comment]
Should be fixed
