### ISSUE TITLE
Going up to a boss floor 18 put me inside a wall

### ISSUE THREAD

**Issue by ShareDVI** [Smujb/yet-another-shattered-dungeon#18]
![photo_2020-07-10_11-51-59](https://user-images.githubusercontent.com/2362022/87136775-a3fe5280-c2a4-11ea-880d-cd1ee1e65dc6.jpg)

I returned upstairs from floor 18 and got inside a wall, with no teleportation or chains working. 
One out-of-ordinary thing I did was setting up a porter on floor 19, not sure if related.

**Comment by Smujb** [comment]
Yeah, this was reported in Cursed and is fixed. Already fixed in YASD but not out yet as I'm porting 0.8.1 Shattered (and on holiday rn) fix might be out next weekend earliest.

**Comment by ShareDVI** [comment]
Sure, have fun on your holiday! I might check out Cursed in the meantime...

**Comment by Smujb** [comment]
Fixed
