### ISSUE TITLE
Damage ranges are sometimes displayed from larger to smaller

### ISSUE THREAD

**Issue by ShareDVI** [Smujb/yet-another-shattered-dungeon#19]
![photo_2020-07-10_12-01-08](https://user-images.githubusercontent.com/2362022/87137149-24bd4e80-c2a5-11ea-8a83-b3e52104a0e4.jpg)
See here, could be a display bug or (my suspicion) a negative number in the range.

**Comment by Smujb** [comment]
The actual issue here is that multipliers only affect max damage. Closing this as melee weapons have a fix that prevents max damage being less than minimum, and armours no longer have a blocking range, only a fixed number.
