### ISSUE TITLE
Hard game lockup when bolas hit  Tengu.

### ISSUE THREAD

**Issue by vi** [Smujb/yet-another-shattered-dungeon#22]
commit cc0e775ae9d149b7d357a009307df54d2266d2d3 

All animations stopped, no reaction to clicks at all, no menu or screen panning; eventually game exited.

Nothing interesting in logcat (I don't see any messages from the game at all). Just something like this when the window eventually disappeared:

```
07-19 21:03:53.313  1365  1877 W InputDispatcher: channel '66365b9 com.smujamesb.yasd.indev/com.shatteredpixel.yasd.android.AndroidGame (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-19 21:03:53.314  1365  1877 E InputDispatcher: channel '66365b9 com.smujamesb.yasd.indev/com.shatteredpixel.yasd.android.AndroidGame (server)' ~ Channel is unrecoverably broken and will be disposed!
```

**Comment by vi** [comment]
Update: I see the `07-19 21:03:21.808 26224 26556 I GAME    : -- Tengu: "Gotcha, huntress!"` message in logcat.

After that it's just things about AlarmManager.

The problem is reproducible after reloading the savefile.

Here is screenshot of the frozen moment:

![4](https://user-images.githubusercontent.com/173219/87881823-8055ad80-ca04-11ea-85b1-b90310630f3f.png)

**Comment by vi** [comment]
Here is game state dump (which probably includes the savefile):

https://vi-server.org/pub/yasd_issue_22.tar.gz

**Comment by vi** [comment]
If begin the batte in some other way than throwing a bolas (e.g. attacking directly and only then throwing a bolas), the bug does not reproduce.

**Comment by Smujb** [comment]
Thanks for all the info, I'll look into it when I can

**Comment by Smujb** [comment]
Fixed by https://github.com/Smujb/yet-another-shattered-dungeon/commit/3eb05979044e5e8f483ccb4ad59cdfc9b7e31747
