### ISSUE TITLE
"Can't carry: potion of healing"

### ISSUE THREAD

**Issue by vi** [Smujb/yet-another-shattered-dungeon#23]
With fully stuffed main inventory, but a plenty of room in the bandolier (which includes a stack of PoH-s).

commit d7fc078fe967bf759705ef3216cb24308e6b0eb0

**Comment by Smujb** [comment]
Fixed by https://github.com/Smujb/yet-another-shattered-dungeon/commit/bdeb9c01db12ab4ecd5e933d4041d82816fb798b
