### ISSUE TITLE
Crush and deleting save on surfacing

### ISSUE THREAD

**Issue by Xazmadan** [Smujb/yet-another-shattered-dungeon#25]
error log
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: xiaomi
Device: daisy_sprout
Model: Mi A2 Lite
Manufacturer: Xiaomi
Product: daisy
SDK: 29
Release: 10

***** APP INFO 
Version: 0.4.8a-INDEV
Installed On: 2020-07-31 17:44:13
Updated On: 2020-07-31 17:44:13
Current Date: 2020-08-06 15:19:29

***** ERROR LOG 
java.lang.NullPointerException: Attempt to read from null array
	at com.shatteredpixel.yasd.general.actors.buffs.Preparation.act(Preparation.java:124)
	at com.shatteredpixel.yasd.general.actors.Actor.process(Actor.java:271)
	at com.shatteredpixel.yasd.general.scenes.GameScene$2.run(GameScene.java:582)

***** END OF LOG *****

**Comment by Smujb** [comment]
Fixed by: https://github.com/Smujb/yet-another-shattered-dungeon/commit/4660b0bfc4462e9fa6f2c4973377519750ee710f (not yet public)
