### ISSUE TITLE
Issues as of 0.4.9

### ISSUE THREAD

**Issue by vi** [Smujb/yet-another-shattered-dungeon#30]
10a8fbb208da790db92000f9dd12bae2f2a2cf2d

1. Diving out still resulted in being near water, not above it. I remember this bug being fixed at least twice. Can't it just generate dive-in-dive-out location pairs once per depth and not rely on any calculation results to be matching for diving out to work correctly? I.e. only calculate locations where you can dive in (and where it leads to underwater), processing diving out just using table lookups, not coordinate calculations.
2. Some sprites are missing (e.g. scroll of divination).

**Comment by Smujb** [comment]
2 is known. As for 1, that's not actually possible on the current engine

**Comment by vi** [comment]
https://vi-server.org/pub/yapdbug30.mp4

Seed: 3945743078123
Depth: 7

**Comment by vi** [comment]
> that's not actually possible on the current engine

Then maybe a fuzzing test can be generated?

Level generator is run in a loop. For each generated level:

1. Assert that number of deep water tiles matches the number of light-from-above tiles. If applicable, also assert there are no more than once entry/exit occupying the same tile and that they don't match main depth staircases.
2. Iterate each deep water tile. Dive in there, then immediately dive out. Assert that we are back on the same deep water tile.

**Comment by Smujb** [comment]
This requires rapidly loading and unloading levels (yes, only *one* can ever be loaded at a given time) which will freeze up.

**Comment by vi** [comment]
Subissue 3. The text for describing skill levels say "One point of strength per 3 points invested", but it seems that scheme is now simplified and it is now one to one. The same for Focus.

**Comment by vi** [comment]
> which will freeze up

What do you mean? That level loader is buggy and if you keep on generating levels more and more it will eventually freeze up?

Or that loading and unloading levels would dominate CPU time, compared to checking diving bijection?

Or that this process would not stop and run endlessly, locking up the game?

**Comment by Smujb** [comment]
Loading a level takes 400ms on my device. Repeatedly loading and unloading will take forever and probably freeze up the render thread.

**Comment by vi** [comment]
Just turn off rendering at all for this mode. It is not intended to be a part of normal playing mode, just a development tool.

As soon as discrepancy found, it should output seed&depth, then exit. If everything is OK, just run forever. For 400ms I expect about 50k dives to happen if the app is run overnight. Not that much for a fuzz test, but better than nothing.

**Comment by vi** [comment]
Also freezing things because of just too much things happening it also a [latent] bug.

**Comment by vi** [comment]
# Subissue 4.

Difficulty selection is misaligned. May be caused by Power Saver mode

![screen3](https://user-images.githubusercontent.com/173219/90548116-26780d00-e195-11ea-96df-1cbcf07f29a2.png)

# Subissue 5.

After falling down in Distant Well room, no bone remains.

![screen1](https://user-images.githubusercontent.com/173219/90548110-2546e000-e195-11ea-84dc-0e58f120aa30.png)
![screen2](https://user-images.githubusercontent.com/173219/90548115-25df7680-e195-11ea-9eec-7ab15e8c4947.png)

Fortunately, deep water is present.

After a while I found out that I have the key for that door (I don't remember where exactly I picked it).

**Comment by vi** [comment]
# Subissue 6.

Unless it's deliberate gameplay change, I don't see any "locked on target" mark for Sniper. Or is this part of Shattered is not yet or not intended to be ported?

**Comment by Smujb** [comment]
Nope, it's not intended. I'll have to fix.

**Comment by vi** [comment]
Also are Scrolls of Upgrade supposed to be fireproof like in Shattered?

**Comment by Smujb** [comment]
No, idk why they are

**Comment by vi** [comment]
> No, idk why they are

Items that have constant quantity (SoU and PoS) are protected from accidental destruction in Shattered.

**Comment by vi** [comment]
# Subissue 7

Hero steps into a recently discovered trap.

In Shattered hero routes around it automatically.

**Comment by Smujb** [comment]
So many subissues at this point you should probably create a new one. This is known and it's a bug with the map flags cache; disable it in development settings and you'll see this doesn't happen, but performance may be reduced.

**Comment by Smujb** [comment]
![image](https://user-images.githubusercontent.com/15002583/90806160-8943e280-e314-11ea-90f8-8da48661ea5a.png)
Reproduced your bones bug.

**Comment by Smujb** [comment]
So yep, I've added a way to enter seeds on debug mode so I can play other people's games.

**Comment by Smujb** [comment]
The remaining issue here, "hero doesn't route around traps" is now fixed indev. For now, disabling the map flags cache should prevent this ever happening.
