### ISSUE TITLE
can't go on caves level, no special must to do anything, just can't go, at all

### ISSUE THREAD

**Issue by Xazmadan** [Smujb/yet-another-shattered-dungeon#31]
error log:
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: xiaomi
Device: daisy_sprout
Model: Mi A2 Lite
Manufacturer: Xiaomi
Product: daisy
SDK: 29
Release: 10

***** APP INFO 
Version: 0.4.9-INDEV
Installed On: 2020-07-31 17:44:13
Updated On: 2020-08-17 18:17:36
Current Date: 2020-08-18 17:15:58

***** ERROR LOG 
java.lang.NullPointerException: Attempt to read from null array
	at com.shatteredpixel.yasd.general.actors.buffs.Preparation.act(Preparation.java:128)
	at com.shatteredpixel.yasd.general.actors.Actor.process(Actor.java:271)
	at com.shatteredpixel.yasd.general.scenes.GameScene$2.run(GameScene.java:582)

***** END OF LOG *****

**Comment by Smujb** [comment]
Fixed by https://github.com/Smujb/yet-another-shattered-dungeon/commit/26880780b83341fcc989348fb23c548f0d10d8e7. Assassin's "preparation" buff failed to account for enemies who haven't acted yet.
