### ISSUE TITLE
When going down to DM-300 level, you stuck in the wall, there is no way to escape, only death

### ISSUE THREAD

**Issue by Xazmadan** [Smujb/yet-another-shattered-dungeon#33]
![Screenshot_20200820-215031.png](https://user-images.githubusercontent.com/69046303/90813144-cf5a6f80-e32f-11ea-90c3-483a8a06e724.png)

**Comment by Smujb** [comment]
Fixed by https://github.com/Smujb/yet-another-shattered-dungeon/commit/03b2e7c80d11cf7ecd4ff845ab468f5d4f94bc1a. Funnily enough I fixed this in Cursed ages ago, but forgot to port the fix to YASD/Powered.
