### ISSUE TITLE
sometimes when leave to the main menu and loading back, wand's max charges lose 1-3 points, and they have overcharges

### ISSUE THREAD

**Issue by Xazmadan** [Smujb/yet-another-shattered-dungeon#34]
![Screenshot_20200822-075359.png](https://user-images.githubusercontent.com/69046303/90949045-6b2dcd80-e44d-11ea-9310-d0e48643e0db.png)

**Comment by Smujb** [comment]
Fixed by https://github.com/Smujb/yet-another-shattered-dungeon/commit/5c422d2d671852e50345080d06b74b0a3e780a11
