### ISSUE TITLE
physical and maybe magical protection doesn't work

### ISSUE THREAD

**Issue by Xazmadan** [Smujb/yet-another-shattered-dungeon#35]
when i equipped 3 armors on +40% +33% +29% physical defence, enemy still damaged me, like with not armor. Enemys was a: monk, gnoll brute, dm-300, cave spider, all sewers mobs, prison guard, fly swarm.

**Comment by Xazmadan** [comment]
in previous update i don't receive any physical damage, including damage from  Chalice of blood

**Comment by Smujb** [comment]
I'm pretty sure they stack multiplicatively. I'll look into it but it's not a case of adding the percentages up.

**Comment by Xazmadan** [comment]
But in that update damage from Chalice of blood is too don't decreased

**Comment by Smujb** [comment]
Well if it changed between updates that's incredibly odd, as I didn't touch armour code...

**Comment by Smujb** [comment]
Closing this as they seem to work fine from my testing. There *was* a bug however where magical and physical damage might apply wrongly to different sources, and this was fixed by https://github.com/Smujb/yet-another-shattered-dungeon/commit/3c66141b1fccf7f72678a820bc9d1fb1b934d857

**Comment by Smujb** [comment]
It was based on shielding level so the difference you experienced was likely based on whether your shield was full rather than updating the game.
