### ISSUE TITLE
Dwarf king just don't dies when he must. He don't summon enemies, just staring at you

### ISSUE THREAD

**Issue by Xazmadan** [Smujb/yet-another-shattered-dungeon#36]
![Screenshot_20200827-121057.png](https://user-images.githubusercontent.com/69046303/91421994-45defc00-e85f-11ea-97a2-ef6337f083fe.png)

**Comment by Smujb** [comment]
Fixed by https://github.com/Smujb/yet-another-shattered-dungeon/commit/ff8053bbcccfb8d4b696f40ade4df5bacb9ecdf6
