### ISSUE TITLE
Wand of stone bolt with 0 charges, lol wat

### ISSUE THREAD

**Issue by Xazmadan** [Smujb/yet-another-shattered-dungeon#37]
![Screenshot_20200901-211504.png](https://user-images.githubusercontent.com/69046303/91890892-ce62ff80-ec98-11ea-8817-a1318c4c9b69.png)

**Comment by Smujb** [comment]
Closing as it's a copy of https://github.com/Smujb/yet-another-shattered-dungeon/issues/40
