### ISSUE TITLE
wand's max charges decreases on 2-3 when relaunch

### ISSUE THREAD

**Issue by Xazmadan** [Smujb/yet-another-shattered-dungeon#40]
i remember you say what it was fixed, but wand with 0 charges and then poison wand with 3/1 charges(sorry but scsh not avalible) is proof what it was returned

**Comment by Smujb** [comment]
Yeah, I thought it was fixed but I guess not

**Comment by Smujb** [comment]
Fixed by https://github.com/Smujb/yet-another-shattered-dungeon/commit/56126ede0ddeac4ae48336435f184d8fc5259e55
