### ISSUE TITLE
Sacrificial fire

### ISSUE THREAD

**Issue by Gammalolman** [Smujb/yet-another-shattered-dungeon#42]
hello there. Playing version 0.4.10 indev. I found sacrificial fire on floor 3 (which has no description) and, hearing that it now attracts mobs to you by setting stealth to 0, I decided to step on it and wait for mobs to come.... and wait.... and wait....
Eventually, I walked around.... and noticed that it doesn't set stealth to 0. It seems to set perception of enemies to 0, as no enemy could see me aside from after a surprise attack and I could surprise attack them multiple times. Meaning that it went from a tedius grind to an impossible task that also has an huge benefit.

**Comment by Smujb** [comment]
The fix was only released in Cursed yet

**Comment by Smujb** [comment]
I'll keep this open as a reminder to fix up the stealth system

**Comment by Gammalolman** [comment]
then why was it written in the powered changelog as well?

**Comment by Smujb** [comment]
Wait was it? Hmm, maybe I did port it

**Comment by Smujb** [comment]
Unsure if it's in APK; it's here at line 660 https://www.github.com/Smujb/yet-another-shattered-dungeon/tree/master/core%2Fsrc%2Fmain%2Fjava%2Fcom%2Fshatteredpixel%2Fyasd%2Fgeneral%2Factors%2FChar.java

**Comment by Smujb** [comment]
It has no effect whatsoever on enemies. Literally just makes stealth return 0

**Comment by Gammalolman** [comment]
checked the link you sent.... there is.... nothing in line 660?

**Comment by Smujb** [comment]
It'll be near that then? Char.sneakSkill()

**Comment by Gammalolman** [comment]
Yep I found it. I'll make a video to show what happens in apk.

**Comment by Gammalolman** [comment]
https://cdn.discordapp.com/attachments/644470102414327819/754329452950847488/SVID_20200912_151418_1.mp4

**Comment by Smujb** [comment]
Fixed by https://github.com/Smujb/yet-another-shattered-dungeon/commit/276ae29ec8f8f504c9b4c7b58f1e3b4012e548af
