### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by vi** [Smujb/yet-another-shattered-dungeon#6]
```

***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: google
Device: crosshatch
Model: Pixel 3 XL
Manufacturer: Google
Product: crosshatch
SDK: 29
Release: 10

***** APP INFO 
Version: 0.4.2a-INDEV
Installed On: 2020-02-18 00:23:16
Updated On: 2020-06-10 16:42:18
Current Date: 2020-06-10 22:04:56

***** ERROR LOG 
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.shatteredpixel.yasd.general.sprites.CharSprite.showStatus(int, java.lang.String, java.lang.Object[])' on a null object reference
	at com.shatteredpixel.yasd.general.actors.mobs.Mob.remove(Mob.java:527)
	at com.shatteredpixel.yasd.general.actors.buffs.Buff.detach(Buff.java:96)
	at com.shatteredpixel.yasd.general.actors.buffs.FlavourBuff.act(FlavourBuff.java:39)
	at com.shatteredpixel.yasd.general.actors.Actor.process(Actor.java:263)
	at com.shatteredpixel.yasd.general.scenes.GameScene$2.run(GameScene.java:579)



***** END OF LOG *****


```

commit  e553e8ca0894c578f507afca8832a3c7798adfea

---

Also item stats and properties look wild and randomized. The same item type, same tier, same upgradeness, yet drastically different stats and strong/weak points (although mostly still in tune with type). Also sometimes I get reversed "minimum-maximum" range, such as great shield's "2-1" attack while other great shied has "1-7" attack (or something like that).

In general at current game state it seems to be relatively easy to build an impenetrable "turtle" build with ethereal+other armor and receive "0" for vast majority of enemy hits.

**Comment by Smujb** [comment]
Item propeprties look randomised because they are. As for the crash, I'm on it.

**Comment by Smujb** [comment]
Fixed by https://github.com/Smujb/yet-another-shattered-dungeon/commit/d35c4f2c0fdd12bd22a264a07c63d1dff9ae8bd9

**Comment by vi** [comment]
> Item properties look randomized because they are.

But description text showing reversed ranges like `2-1` or strange extra inner spaces like `7- 1` is suspicious. As if some negative numbers started appearing where nonnegatives are expected.

**Comment by Smujb** [comment]
That part is mainly due to the multiplier only affecting max damage. I should probably change it so it can't go below min dmg.
